# Generated by Django 3.0.6 on 2020-05-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=5)),
                ('items', models.CharField(max_length=50)),
                ('cnic', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
    ]
