# Generated by Django 3.0.6 on 2020-05-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200516_0212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='food',
            new_name='foodorders',
        ),
    ]
