# Generated by Django 3.0.6 on 2020-05-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=50)),
                ('feed', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='feed',
        ),
    ]
