# Generated by Django 3.0.6 on 2020-05-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20200516_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='feed',
            field=models.TextField(max_length=500),
        ),
    ]
