# Generated by Django 3.0.6 on 2020-05-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20200516_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('room_type', models.CharField(max_length=50)),
                ('adults', models.CharField(max_length=20)),
                ('children', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='reservation',
        ),
    ]
